name: dart_websocket
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  args: ^2.0.0
  graphql: ^5.0.1
  http: ^0.13.4
  mongo_dart: ^0.7.4
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
  build_web_compilers: ^3.2.2
  build_runner: ^2.1.8
